### PR TITLE
GenAI - Ramp up - Amazon SageMaker Jumpstart

### PR DESCRIPTION
**Pull request by pymia**
The original GenAI lab includes the content straight to the Amazon SageMaker and integrates with other services. 

The developers of AI service like Amazon Textract and Amazon Comprehend, who have experienced REST API call and less experience with Amazon SageMaker. Hence, this notebook provides the developers an opportunity to ramp up the Amazon SageMaker skills.

In this notebook, we show: (1) How to deploy a LLM in Amazon SageMaker JumpStart, (2) Common use cases of LLMs, and (3) How to ask a question to a LLM with and without providing the context. The expected effort will take about 15 mins to run through the whole notebook, including 5-10 minutes model deployment.

Through the samples in the notebook, developers can learn the basic of Amazon SageMaker Jumpstart, Model deployment, and prompt to start their learning of 01-idp-genai-qna.ipynb.

*Issue #, if available:*
NA

*Description of changes:*
Add Amazon SageMaker Jumpstart notebook

*Note*
A joint PR of miachang@ and klssmk@.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by davidgirling — COMMENTED** [review]
Hey Mia,
FYI
I did run through the notebook in SM, but it didn't work for me, had incompatible python dependency libraries.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
distributed 2022.7.0 requires tornado<6.2,>=6.0.3, but you have tornado 6.3.2 which is incompatible.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.3.3 requires pyqt5<5.16, which is not installed.
spyder 5.3.3 requires pyqtwebengine<5.16, which is not installed.
jupyterlab 3.4.4 requires jupyter-server~=1.16, but you have jupyter-server 2.7.0 which is incompatible.
jupyterlab-server 2.10.3 requires jupyter-server~=1.4, but you have jupyter-server 2.7.0 which is incompatible.
sagemaker-datawrangler 0.4.3 requires sagemaker-data-insights==0.4.0, but you have sagemaker-data-insights 0.3.3 which is incompatible.
spyder 5.3.3 requires ipython<8.0.0,>=7.31.1, but you have ipython 8.14.0 which is incompatible.
spyder 5.3.3 requires pylint<3.0,>=2.5.0, but you have pylint 3.0.0a6 which is incompatible.
spyder-kernels 2.3.3 requires ipython<8,>=7.31.1; python_version >= "3", but you have ipython 8.14.0 which is incompatible.

**Comment by klssmk** [comment]
Hi David, 

Did you continue through the workshop after you received the error messages? I'm able to successfully complete the lab as is. Please let me know

**Comment by davidgirling** [comment]
I went back and reran, was able to complete the notebook with the error message as is too.

Thanks.

**Comment by klssmk** [comment]
Thank you. Am I required to make any changes in order to get this approved?

**Review by chinrane — APPROVED** [review]

**Review by davidgirling — APPROVED** [review]

**Pull request merged**
